name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' # Or choose another distribution if required (e.g., 'zulu', 'adopt').

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the application
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Run tests
      - name: Run tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    #  - name: Deploy to Server
    #    env:
    #      SERVER_IP: ${{ secrets.SERVER_IP }}
    #      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
    #      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    #    run: |
    #      echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
    #      chmod 600 ~/.ssh/id_rsa
    #      scp target/my-app.jar ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }}:/path/to/deployment
    #      ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} "java -jar /path/to/deployment/my-app.jar"
